name: ws-gateway

on: push

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Integration test
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do test